# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: Install_Run_SAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull qaregistry.fortinet.com/fortidevsec/fdevsec_sast:latest
      docker run --rm  --mount type=bind,source="$PWD",target=/scan qaregistry.fortinet.com/fortidevsec/fdevsec_sast:latest
- task: Bash@3
  displayName: Install_Run_DAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull qaregistry.fortinet.com/fortidevsec/fdevsec_dast:latest
      docker run --rm  --mount type=bind,source="$PWD",target=/scan qaregistry.fortinet.com/fortidevsec/fdevsec_dast:latest
