trigger:
  - main
pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  displayName: Install_Run_SAST
  inputs:
    targetType: 'inline'
    script: |
	env
	env | grep -E "EMAIL|LICENSE_SERIAL|ASSET_TOKEN|SCANURL|SCANTYPE|ASSET" > /tmp/env
	docker pull registry.fortidast.forticloud.com/dastdevopsproxy:latest
	docker run --rm --env-file /tmp/env --network=host registry.fortidast.forticloud.com/dastdevopsproxy:latest
