trigger:
- feature/add_azure_pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: Install_Run_SAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull registry.fortinet.com/fortidevsec/fdevsec_sast:latest
      docker run --rm  --mount type=bind,source="$PWD",target=/scan registry.fortinet.com/fortidevsec/fdevsec_sast:latest
- task: Bash@3
  displayName: Install_Run_DAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull registry.fortinet.com/fortidevsec/fdevsec_dast:latest
      docker run --rm  --mount type=bind,source="$PWD",target=/scan registry.fortinet.com/fortidevsec/fdevsec_dast:latest
