trigger:
  - main
pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  displayName: Install_Run_SAST
  inputs:
    targetType: 'inline'
    script: |
      env
      env | grep -E "AZURE_HTTP_USER_AGENT|BUILD_BUILDID" > /tmp/env
      docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      docker run --rm  --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest

