trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  displayName: Install_Run_SAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      docker run --rm  --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
