trigger:
   branches:
     include:
       - main
   resources:
     repositories:
     - repository: self
       type: git
       ref: main
   jobs:
   - job: Job_1
     displayName: Scan
     condition: succeededOrFailed()
     pool:
      name: Default

   steps:
    - checkout: self
    - task: PowerShell@2
      displayName: SAST
      inputs:
        targetType: inline
        script: >
          docker run --rm --mount type=bind,source=$PWD,target=/scan dops-registry.fortinet-us.com/fortidevsecops/fdevsec_sast:latest
    - task: PowerShell@2
      displayName: DAST
      inputs:
        targetType: inline
        script: >
          docker run --rm --mount type=bind,source=$PWD,target=/scan dops-registry.fortinet-us.com/fortidevsecops/fdevsec_dast:latest
