# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: Install_Run_SAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull fedora
      docker run hello-world
- task: Bash@3
  displayName: Install_Run_DAST
  inputs:
    targetType: 'inline'
    script: |
      docker pull debian
      docker run hello-world
